name: publish-pypi

on:
  workflow_dispatch:
    inputs:
      pypi-package-version:
        description: Package version
        required: true
        type: string

jobs:
  publish-pypi:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - env:
          PYTHON_VERSION: "3.11"
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - env:
          PACKAGE_VERSION: ${{ inputs.pypi-package-version }}
        name: Prepare
        run: pip install wheel && python setup.py sdist bdist_wheel
      - name: Publish PyPi
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
